### PR TITLE
Fixes for user scroll problem.

### PR DESCRIPTION
**Pull request by Randy1Burrell**
When ever a user scroll on dash.org the navigation bar disappears. This may be bad for user experience because when they are at the bottom/middle of page it can be tedious to go back to top in order to find the navigation bar to navigate elsewhere on the site. This pull request tries to rectify the issue by adding a scroll to top link on the right bottom corner of the site when the user scrolls the navigation bar out of sight. Css and js makes button look appealing and scrolling smooth when link is clicked. #408

### CODE REVIEW

**Comment by mrleewong** [comment]
```
+<div class="container direction-container" >
 +	<ul class="direction" id="topBtn">
 +		<li>
 +			<a id="to_top" href="#top">
 +				Top &uarr;
 +			</a>
 +		</li>
 +	</ul>
 +</div>
```
Unnecessary wrapper for to Top button. It could be a simple <a></a> or button.

` _includes/globals_js_data.html
`
We are using this file only for global data or configs, and keeping html code clean from javascript code. We are adding new functional in separate new\existing files.

`$('a[href*="#"]')
`
Not the best solution when you filter all links that contains hashes.
Better to match and work with specific collection without unnecessary elements. In this case would be better to match with specific js-class or id and sort out with them.

`document.getElementById("topBtn") `

Could you please follow DRY(do not repeat yourself)principle. It could be like:
> var elementName = document.getElementById("topBtn”);
and then working with this variable.


`document.getElementById("topBtn").style.visibility = "visible"; document.getElementById("topBtn").style.opacity = "1";`
Is it the same functionality, isn't it?
In this case better to animate opacity from 0 to 1 or 1 to 0 (when we hide) and add style on callback `display: none/block.`

`<a name="top">`
 Name attribute is deprecated and not valid in html5 and would be better to use id.
And also a tags must be closed otherwise its not valid html markup.
This element is unnecessary, better to add simple id/class to navigation and working with them.

`#topBtn
`
 Id in css has a more weight than class, and better to use only Classes in css.

>-webkit-transition 

We are using post css autoperfixer, this and below prefixes are unnecessary.


I have to notice thats solution could be more usefull with a function something like “scroll to element” and match with them by classes\id instead of using specific function only for to top button.

**Comment by chuckwilliams37** [comment]
Thanks, @mrleewong for the detailed review. I'm grateful to have your eyes on this, as my look was only cursory and I failed to give it an "educator's attention", as you have. 

Functionality-wise, This past Tuesday as Randy & I were talking, I saw a screenshot/demo from Randy and I honestly didn't understand what he was trying to accomplish without building the app, until I saw his screenshots.  

After seeing it, and thinking about it's value, I think it's worth mentioning @Randy1Burrell that there are many usability studies and UX research articles that soundly demonstrate that vertical scrolling is one of the most "accepted" actions in interfaces.  That is, most people are comfortable with scrolling, and generally do not need (or want) an additional button on their screen to help them scroll to the top. I'm hoping to attract people to the team that are familiar with these types of value judgements.

Thanks for your contribution, @Randy1Burrell !

**Comment by Randy1Burrell** [comment]
Thanks @mrleewong for the detailed review. Your points are really valid and I should never have submitted code with such flaws, especially forgetting to close my html tags is a mistake that must not be made. Given being pressed for time and internet connectivity issues at the time of submitting this PR, I made these mistakes. My apologies, but finally my internet is now back to normal.

@chuckwilliams37 I understand what you are saying about UX feasibility researches that talked about vertical scrolling being acceptable, but that was never my issue with dash.org. As I had mentioned in issue #408, users can sometimes become frustrated with the site if they have to keep scrolling back to the top of your webpage to find the navigation menu after that user has scrolled to the bottom of the page. This is one of the issue that can make or break your user experience and is commonly called "scrolling fatigue", according to [Usability Geek](https://usabilitygeek.com/how-scrolling-can-make-or-break-your-user-experience/). I gave three fixes to this issue in #408 and implemented the easiest fix. Maybe the best fix would have been a "sticky navigation" bar that is always visible when the user scrolls like what can be found on facebook, twitter, and other popular sites with long scrolls, which I suggested in issue #408.

**Comment by chuckwilliams37** [comment]
Thanks again, @Randy1Burrell, for your contribution.  In the article you reference, the relevant sentence reads "...Failure to cluster relevant information throughout key points in a text can lead to a phenomenon called “scrolling fatigue.”..."

By my reading, this means grouping information appropriately (Information Architecture) rather than eating real valuable screen real-estate for for more interactivity (Interaction Design).

Interestingly, I referenced this very issue while I was employed with [Oppenheimer funds](https://www.oppenheimerfunds.com/investors), and I helped to implement a system of presentation that I believe "...cluster[s] relevant information throughout key points..." on both desktop and web, and does not get overly intrusive by duplicating existing interaction capability (scrolling).

[See an example of that work here.](https://www.oppenheimerfunds.com/investors/fund/capital-appreciation-fund/00320)

**Comment by Randy1Burrell** [comment]
@chuckwilliams37 Thank you for your insight. I believe in continuous self development so I appreciate your  thoughts and expert advice as I continue to strive towards excelling in my field. Again, thank you.

**Pull request closed without merging**
